// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkMvsRCoHbNIctIadaBf2n3P8BItu_aWQ',
    appId: '1:96354871752:android:17f9d8d7e20d1b4b9cb8fd',
    messagingSenderId: '96354871752',
    projectId: 'mytech-535f2',
    storageBucket: 'mytech-535f2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBw6xrL5eaXGllHT0XFu1goXv2ts2CxkY',
    appId: '1:96354871752:web:1810e9512e5d4e0e9cb8fd',
    messagingSenderId: '96354871752',
    projectId: 'mytech-535f2',
    authDomain: 'mytech-535f2.firebaseapp.com',
    storageBucket: 'mytech-535f2.firebasestorage.app',
    measurementId: 'G-SGXL6378PS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_32Ab8GIYSZb7iK9LupI9LjBK7oNiGA',
    appId: '1:96354871752:ios:58261c7a020374999cb8fd',
    messagingSenderId: '96354871752',
    projectId: 'mytech-535f2',
    storageBucket: 'mytech-535f2.firebasestorage.app',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_32Ab8GIYSZb7iK9LupI9LjBK7oNiGA',
    appId: '1:96354871752:ios:58261c7a020374999cb8fd',
    messagingSenderId: '96354871752',
    projectId: 'mytech-535f2',
    storageBucket: 'mytech-535f2.firebasestorage.app',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBw6xrL5eaXGllHT0XFu1goXv2ts2CxkY',
    appId: '1:96354871752:web:7cb82d3c9e163ef39cb8fd',
    messagingSenderId: '96354871752',
    projectId: 'mytech-535f2',
    authDomain: 'mytech-535f2.firebaseapp.com',
    storageBucket: 'mytech-535f2.firebasestorage.app',
    measurementId: 'G-5XYLK5P0Y6',
  );

}